/**
 * Generates the source text of the standalone capture-hook script `record`
 * writes to disk and points its inserted settings entries at.
 *
 * @remarks
 * Dynamic layer, but this module itself performs no I/O — `session.ts` is
 * what writes the string this builds to disk. The generated script is a
 * plain CommonJS file (`.cjs`, so it runs the same way regardless of the
 * target project's own `package.json#type`) with zero dependencies of its
 * own: it never `require()`s this package, only `node:fs`, `node:path`, and
 * `node:crypto`, because it runs as a real Claude Code hook process, in a
 * project this package may not even be installed in as anything but a dev
 * dependency of the checkout `record` was run from.
 *
 * Because the generated text only ever runs inside a spawned child process,
 * `placing-tests`' "coverage stops at the process boundary" applies: nothing
 * in the string body itself is instrumented by `pnpm test:coverage`. What
 * `pnpm test:coverage` does measure is `buildCaptureScript` itself (a normal
 * TypeScript function returning a string), so its own branches — every
 * `JSON.stringify`d option — are covered the ordinary way; `tests/record.test.ts`
 * additionally spawns the generated text as a real process to prove its
 * runtime behavior (exit 0, no stdout, the written envelope's shape), which
 * `pnpm test:coverage`'s floor does not require but this issue's acceptance
 * criteria do.
 */

/** The generated capture script's own filename, relative to its containing directory. */
export const CAPTURE_SCRIPT_FILENAME = "capture-hook.cjs";

/** What `buildCaptureScript` needs to know to generate one project's capture script. */
export interface CaptureScriptOptions {
  /** Absolute path of the directory captured payload envelopes are written into. */
  readonly captureDir: string;

  /**
   * The Claude Code version to fall back to when the captured payload itself
   * carries none, and `HOOKASSERT_CLAUDE_VERSION` is unset at hook-run time.
   *
   * @remarks
   * Baked into the generated script as a literal, because the script runs as
   * its own process later, under Claude Code — it can never see the
   * `--claude-version` flag `record` itself was given.
   */
  readonly claudeVersionFlag: string | undefined;

  /**
   * Absolute path of the file to (over)write with the most recently captured
   * *known* `claudeVersion` — see
   * `src/internal/record/session.ts`'s `lastRecordedClaudeVersionPath`.
   *
   * @remarks
   * Never written when the resolved `claudeVersion` is `"undetermined"`: a
   * capture that could not determine a version must not clobber a previous
   * capture's real one.
   */
  readonly lastVersionFile: string;
}

/**
 * Build the capture-hook script's full source text.
 *
 * @remarks
 * The script always exits `0` and writes nothing to stdout, whether the
 * capture itself succeeded or not — see the design section this issue's
 * `record` implements: "it must never change any existing hook's behavior".
 * Every failure mode (stdin not valid JSON, the capture directory could not
 * be created, the write itself failed) is caught and silently ignored rather
 * than surfaced, for the same reason.
 */
export function buildCaptureScript(options: CaptureScriptOptions): string {
  const captureDir = JSON.stringify(options.captureDir);
  const bakedClaudeVersion = JSON.stringify(options.claudeVersionFlag ?? null);
  const lastVersionFile = JSON.stringify(options.lastVersionFile);

  return `#!/usr/bin/env node
"use strict";

/**
 * Generated by \`hookassert record\`. Reads one Claude Code hook payload from
 * stdin, writes it to its own envelope file under the capture directory
 * below, and always exits 0 with nothing on stdout — it must never change
 * the behavior of the hook invocation Claude Code made it part of.
 */

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const CAPTURE_DIR = ${captureDir};
const BAKED_CLAUDE_VERSION = ${bakedClaudeVersion};
const LAST_VERSION_FILE = ${lastVersionFile};

const chunks = [];
process.stdin.on("data", (chunk) => {
  chunks.push(chunk);
});
process.stdin.on("error", () => {
  process.exit(0);
});
process.stdin.on("end", () => {
  try {
    const raw = Buffer.concat(chunks).toString("utf8");

    let payload;
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = undefined;
    }

    const isRecord = payload !== null && typeof payload === "object" && !Array.isArray(payload);
    const event =
      isRecord && typeof payload.hook_event_name === "string"
        ? payload.hook_event_name
        : "unknown";
    const payloadVersion =
      isRecord && typeof payload.version === "string" && payload.version.length > 0
        ? payload.version
        : undefined;
    const envVersion =
      typeof process.env.HOOKASSERT_CLAUDE_VERSION === "string" &&
      process.env.HOOKASSERT_CLAUDE_VERSION.length > 0
        ? process.env.HOOKASSERT_CLAUDE_VERSION
        : undefined;
    const claudeVersion =
      payloadVersion ?? envVersion ?? BAKED_CLAUDE_VERSION ?? "undetermined";

    fs.mkdirSync(CAPTURE_DIR, { recursive: true });

    const capturedAt = new Date().toISOString();
    const suffix = crypto.randomBytes(6).toString("hex");
    const fileName = "capture-" + capturedAt.replace(/[:.]/g, "-") + "-" + suffix + ".json";
    const filePath = path.join(CAPTURE_DIR, fileName);

    const envelope = {
      capturedAt,
      event,
      claudeVersion,
      sourceFile: filePath,
      payload: payload === undefined ? { raw } : payload,
    };

    fs.writeFileSync(filePath, JSON.stringify(envelope, null, 2) + "\\n", "utf8");

    if (claudeVersion !== "undetermined") {
      try {
        fs.writeFileSync(
          LAST_VERSION_FILE,
          JSON.stringify({ claudeVersion, capturedAt }, null, 2) + "\\n",
          "utf8",
        );
      } catch {
        // Best-effort bookkeeping only; never lets a capture fail over it.
      }
    }
  } catch {
    // A capture failure must never surface: this script's only contract is
    // "exit 0, print nothing" — see buildCaptureScript's own doc comment.
  }
  process.exit(0);
});
`;
}
